packages:
  - apps/**
  - packages/**
  - '!**/dist/**'

catalog:
  '@proj-airi/drizzle-duckdb-wasm': ^0.4.27
  '@xsai/embed': ^0.3.0-beta.4
  '@xsai/shared': ^0.3.0-beta.4
  '@xsai/shared-chat': ^0.3.0-beta.4
  '@xsai/utils-chat': ^0.3.0-beta.4

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - unrs-resolver
  - vue-demi
