import { boolean, integer, json, pgSchema, real, smallint, text, varchar } from 'drizzle-orm/pg-core'

const postgresInformationSchema = pgSchema('information_schema')

export const postgresInformationSchemaTables = postgresInformationSchema.table('tables', {
  table_catalog: text(),
  table_schema: text(),
  table_name: text().notNull(),
  table_type: varchar(),
  self_referencing_column_name: text(),
  reference_generation: varchar(),
  user_defined_type_catalog: text(),
  user_defined_type_schema: text(),
  user_defined_type_name: text(),
  is_insertable_into: varchar(),
  is_typed: varchar(),
  commit_action: varchar(),
})

export const postgresInformationSchemaColumns = postgresInformationSchema.table('columns', {
  table_catalog: text(),
  table_schema: text(),
  table_name: text(),
  column_name: text(),
  ordinal_position: integer(),
  column_default: varchar(),
  is_nullable: varchar(),
  data_type: varchar(),
  character_maximum_length: integer(),
  character_octet_length: integer(),
  numeric_precision: integer(),
  numeric_precision_radix: integer(),
  numeric_scale: integer(),
  datetime_precision: integer(),
  interval_type: varchar(),
  interval_precision: integer(),
  character_set_catalog: text(),
  character_set_schema: text(),
  character_set_name: text(),
  collation_catalog: text(),
  collation_schema: text(),
  collation_name: text(),
  domain_catalog: text(),
  domain_schema: text(),
  domain_name: text(),
  udt_catalog: text(),
  udt_schema: text(),
  udt_name: text(),
  scope_catalog: text(),
  scope_schema: text(),
  scope_name: text(),
  maximum_cardinality: integer(),
  dtd_identifier: text(),
  is_self_referencing: varchar(),
  is_identity: varchar(),
  identity_generation: varchar(),
  identity_start: varchar(),
  identity_increment: varchar(),
  identity_maximum: varchar(),
  identity_minimum: varchar(),
  identity_cycle: varchar(),
  is_generated: varchar(),
  generation_expression: varchar(),
  is_updatable: varchar(),
})

export const postgresPgCatalogPgClass = pgSchema('pg_catalog').table('pg_class', {
  oid: text('oid'),
  relfrozenxid: text('relfrozenxid'),
  relminmxid: text('relminmxid'),
  relacl: text('relacl').array(),
  relnamespace: text('relnamespace'),
  reltype: text('reltype'),
  reloftype: text('reloftype'),
  relowner: text('relowner'),
  relam: text('relam'),
  relfilenode: text('relfilenode'),
  reltablespace: text('reltablespace'),
  relpages: integer('relpages'),
  reltuples: real('reltuples'),
  relallvisible: integer('relallvisible'),
  reltoastrelid: text('reltoastrelid'),
  relhasindex: boolean('relhasindex'),
  relisshared: boolean('relisshared'),
  relpersistence: text('relpersistence'),
  relkind: text('relkind'),
  relnatts: smallint('relnatts'),
  relchecks: smallint('relchecks'),
  relhasrules: boolean('relhasrules'),
  relhastriggers: boolean('relhastriggers'),
  relhassubclass: boolean('relhassubclass'),
  relrowsecurity: boolean('relrowsecurity'),
  relforcerowsecurity: boolean('relforcerowsecurity'),
  relispopulated: boolean('relispopulated'),
  relreplident: text('relreplident'),
  relispartition: boolean('relispartition'),
  relrewrite: text('relrewrite'),
  relname: text('relname'),
  relpartbound: json('relpartbound'),
  reloptions: text('reloptions').array(),
})

export const postgresPgCatalogPgIndex = pgSchema('pg_catalog').table('pg_index', {
  indexrelid:	text('indexrelid'),
  indrelid:	text('indrelid').references(() => postgresPgCatalogPgClass.oid),
  indnatts:	smallint('indnatts'),
  indnkeyatts:	smallint('indnkeyatts'),
  indisunique:	boolean('indisunique'),
  indnullsnotdistinct:	boolean('indnullsnotdistinct'),
  indisprimary:	boolean('indisprimary'),
  indisexclusion:	boolean('indisexclusion'),
  indimmediate:	boolean('indimmediate'),
  indisclustered:	boolean('indisclustered'),
  indisvalid:	boolean('indisvalid'),
  indcheckxmin:	boolean('indcheckxmin'),
  indisready:	boolean('indisready'),
  indislive:	boolean('indislive'),
  indisreplident:	boolean('indisreplident'),
  indkey:	text('indkey').array(),
  indcollation:	text('indcollation').array(),
  indclass:	text('indclass').array(),
  indoption:	text('indoption').array(),
  indexprs:	json('indexprs'),
  indpred:	json('indpred'),
})
